---
- name: Test Connection to my servres
  hosts: web_servers
  become: yes

  tasks:
    - name: update apt packages 
      apt:
        force_apt_get: true
        upgrade: dist
        update_cache: yes
      become: true

    - name: Install nginx on all servers 
      apt: 
        name: nginx
        state: latest
        update_cache: yes

- name: copy index.html webserver 1 
  hosts: web_server_1
  become: yes

  tasks:
    - name: copy index_new.html
      ansible.builtin.copy:
        src: ./www/index1.html
        dest: /var/www/html/index.html
        owner: root
        group: sudo
        mode: "0644"

- name: copy index.html webserver 2 
  hosts: web_server_2
  become: yes
  
  tasks:
    - name: copy index_new.html
      ansible.builtin.copy:
        src: ./www/index2.html
        dest: /var/www/html/index.html
        owner: root
        group: sudo
        mode: "0644"
