---
- name: install zabbix-agent2
  hosts: all
  become: yes
  gather_facts: yes
  roles: 
    - role: zabbix_agent2

- name: connect zabbix-agent2 to zabbix-server
  hosts: zabbix
  become: yes
  gather_facts: yes
  tasks:    
    - include_vars: "./zabbix/zabbix_credentials.yml"
    - name: add zabbix_server to zabbix
      vars:
        ansible_network_os: community.zabbix.zabbix
        ansible_connection: httpapi
        ansible_httpapi_port: 80
        ansible_httpapi_use_ssl: false
        ansible_httpapi_validate_certs: false
        ansible_zabbix_url_path: ""
        ansible_host: "{{ zabbix_ext_ip }}"
      become: false
      community.zabbix.zabbix_host:
        host_name: Zabbix server
        visible_name: Zabbix server
        host_groups:
          - Linux servers
        link_templates:
          - Linux by Zabbix agent
          - Zabbix server health
        status: enabled
        state: present
        inventory_mode: automatic
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "127.0.0.1"
            dns: ""
            port: "10050"

    - name: add vm to zabbix
      vars:
        ansible_network_os: community.zabbix.zabbix
        ansible_connection: httpapi
        ansible_httpapi_port: 80
        ansible_httpapi_use_ssl: false
        ansible_httpapi_validate_certs: false
        ansible_zabbix_url_path: ""
        ansible_host: "{{ zabbix_ext_ip }}"
      become: false
      community.zabbix.zabbix_host:
        host_name: "{{ item }}"
        visible_name: "{{ item }}"
        host_groups:
          - Linux servers
        link_templates:
          - Linux by Zabbix agent
          - Nginx by Zabbix agent
        status: enabled
        state: present
        inventory_mode: automatic
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "{{ hostvars[item].ansible_default_ipv4.address }}"
            dns: ""
            port: "10050"
      loop: "{{ query('inventory_hostnames', 'web_servers') }}"

    - name: add elastic, kibana, bastion to zabbix
      vars:
        ansible_network_os: community.zabbix.zabbix
        ansible_connection: httpapi
        ansible_httpapi_port: 80
        ansible_httpapi_use_ssl: false
        ansible_httpapi_validate_certs: false
        ansible_zabbix_url_path: ""
        ansible_host: "{{ zabbix_ext_ip }}"
      become: false
      community.zabbix.zabbix_host:
        host_name: "{{ item }}"
        visible_name: "{{ item }}"
        host_groups:
          - Linux servers
        link_templates:
          - Linux by Zabbix agent
        status: enabled
        state: present
        inventory_mode: automatic
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "{{ hostvars[item].ansible_default_ipv4.address }}"
            dns: ""
            port: "10050"
      loop: "{{ query('inventory_hostnames', 'all:!web_servers:!zabbix') }}"
